### PR TITLE
Fixed some css and layout issues

### LINKED ISSUE #45: Fix z-index on filterbar
Sometimes the content lays on top of the filterbar.

### LINKED ISSUE #56: Make another layout component
The first page layout and other pages need to have different layouts

### PR DESCRIPTION
**Pull request by johannesloor**
Made two layout wrappers to use as children to layout. One for content pages and one for info page such as the about page. Also fixed some general css issues. 

fixes #45 
fixes #56

### CODE REVIEW

File: src/molecules/header.tsx [hunk 1]
```diff
@@ -33,16 +33,12 @@ const HeaderWrapper = styled.div`
   padding-top: 2%;
   @media (max-width: ${({ theme }) => theme.breakpoints.sm + 'px'}) {
     width: 80%;
-    padding-top: 0%;
-    padding-bottom: 10%;
+    margin-top: 5vh;
```
Comment (axelekwall) [inline src/molecules/header.tsx]: Does this offset depend on the view height? Maybe it's better to offset this by the height of the filter bar?

Comment (johannesloor) [reply src/molecules/header.tsx]: Good thinking, I put It to 50px instead
